# Generated by Django 5.0.3 on 2024-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
