# Generated by Django 5.0.3 on 2024-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('engineer', 'Engineer'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('student', 'Student'), ('employee', 'Employee'), ('artist', 'Artist'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], null=True),
        ),
    ]
