# Generated by Django 5.0.3 on 2024-05-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_contact'),
        ('account', '0010_pointbalance'),
    ]

    operations = [
    ]
