# Generated by Django 5.0.3 on 2024-05-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_0010_contact_0010_pointbalance'),
        ('account', '0011_user_pointbalance'),
    ]

    operations = [
    ]
