# Generated by Django 5.0.3 on 2024-05-10 19:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('modify', 'Modify'), ('cancel', 'Cancel'), ('offers', 'Offers'), ('cancel_without_payment', 'Cancel Without Payment'), ('cancel_over_week', 'cancel_over_week')], default='default_policy', max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('points', models.PositiveIntegerField(default=0)),
                ('points_offers', models.PositiveIntegerField(default=0)),
                ('conditions', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], max_length=3)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiable', models.BooleanField()),
                ('modify_period', models.DurationField(default=datetime.timedelta(0))),
                ('cancellable', models.BooleanField()),
                ('cancel_period', models.DurationField(default=datetime.timedelta(0))),
                ('cancel_without_payment', models.DurationField(default=datetime.timedelta(0))),
                ('cancellation_discount_amount', models.DecimalField(decimal_places=5, default=1, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('passenger_class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=10, null=True)),
                ('trip_type', models.CharField(choices=[('OW', 'One Way'), ('RT', 'Round Trip')], default='OW', max_length=10)),
                ('status', models.CharField(choices=[('CNL', 'Canceled'), ('PPD', 'Postponed'), ('CMP', 'Completed')], default='PPD', max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('outbound_flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_bookings', to='flights.flight')),
                ('return_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='flights.flight')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
