# Generated by Django 5.0.3 on 2024-05-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyAgency',
        ),
    ]
