# Generated by Django 5.0.3 on 2024-04-26 14:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIAWISEPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiable', models.BooleanField(default=True)),
                ('modify_period', models.DurationField(default=datetime.timedelta(0))),
                ('cancellable', models.BooleanField(default=True)),
                ('cancel_period', models.DurationField(default=datetime.timedelta(0))),
                ('cancel_without_payment', models.DurationField(default=datetime.timedelta(0))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
