# Generated by Django 5.0.3 on 2024-05-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_viawisepolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIAWISEPolicy',
        ),
    ]
