# Generated by Django 5.0.3 on 2024-05-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_policyagency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyagency',
            name='user',
        ),
    ]
