# Generated by Django 5.0.3 on 2024-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_agencypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypolicy',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
