# Generated by Django 5.0.3 on 2024-05-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_agencypolicy_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypolicy',
            name='points_offers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
