# Generated by Django 5.0.3 on 2024-05-03 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_agencypolicy_policy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
