# Generated by Django 5.0.3 on 2024-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypolicy',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='agencypolicy',
            name='policy_type',
            field=models.CharField(choices=[('modify', 'Modify'), ('cancel', 'Cancel'), ('offers', 'Offers'), ('cancel_without_payment', 'Cancel Without Payment'), ('cancel_over_week', 'cancel_over_week')], default='default_policy', max_length=100),
        ),
    ]
