# Generated by Django 5.0.3 on 2024-05-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_agencypolicy_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypolicy',
            name='conditions',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
