# Generated by Django 5.0.3 on 2024-03-27 22:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('IATA_code', models.CharField(max_length=3)),
                ('contact_info', models.TextField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField(default=1)),
                ('refundable', models.BooleanField(default=False)),
                ('exchangeable', models.BooleanField(default=False)),
                ('exchangeable_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('cancellation_period', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='RefundedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(default=datetime.datetime.now)),
                ('return_date', models.DateField(default=datetime.datetime.now)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('airportDeparture', models.CharField(max_length=40)),
                ('airportArrival', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('departure_city', models.CharField(default='', max_length=100, null=True)),
                ('destination_city', models.CharField(default='', max_length=100)),
                ('departure_country', models.CharField(default='', max_length=100)),
                ('destination_country', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_id', models.IntegerField(default=0)),
                ('airline_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=2000)),
                ('ratings', models.IntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flights.flight')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
