# Generated by Django 5.0.3 on 2024-05-10 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='return_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
