# Generated by Django 5.0.3 on 2024-05-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='return_date',
        ),
    ]
