# Generated by Django 5.0.3 on 2024-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseatclass',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flightseatclass',
            name='seat_number',
            field=models.IntegerField(default=10, max_length=10),
        ),
    ]
