# Generated by Django 5.0.3 on 2024-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_airplane_seattype_flight_airplane_airplane_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='policy_id',
        ),
        migrations.AlterField(
            model_name='seattype',
            name='business_class',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='seattype',
            name='economy',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='seattype',
            name='first_class',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
