# Generated by Django 5.0.3 on 2024-04-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_policy_policy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airplane',
        ),
        migrations.RemoveField(
            model_name='seattype',
            name='business_class',
        ),
        migrations.RemoveField(
            model_name='seattype',
            name='economy',
        ),
        migrations.RemoveField(
            model_name='seattype',
            name='first_class',
        ),
        migrations.AddField(
            model_name='airline',
            name='airplane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.airplane'),
        ),
        migrations.AddField(
            model_name='seattype',
            name='business_class_capacity',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seattype',
            name='business_class_weight_limit',
            field=models.IntegerField(default=40, null=True),
        ),
        migrations.AddField(
            model_name='seattype',
            name='carry_on_bag_weight_limit',
            field=models.IntegerField(default=8, null=True),
        ),
        migrations.AddField(
            model_name='seattype',
            name='economy_capacity',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seattype',
            name='economy_weight_limit',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AddField(
            model_name='seattype',
            name='excess_weight_fee',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=10),
        ),
        migrations.AddField(
            model_name='seattype',
            name='first_class_capacity',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seattype',
            name='first_class_weight_limit',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
