# Generated by Django 5.0.3 on 2024-04-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_remove_flight_airplane_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='airline_id',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_id',
        ),
    ]
