# Generated by Django 5.0.3 on 2024-04-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_remove_airline_airline_id_remove_policy_policy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='airplane',
        ),
        migrations.AddField(
            model_name='airline',
            name='airline_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airplane',
            name='airpline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.airline'),
        ),
    ]
