# Generated by Django 5.0.3 on 2024-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_remove_airline_airplane_airline_airline_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='airpline',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='airplane',
            old_name='seats',
            new_name='seattype',
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
