# Generated by Django 5.0.3 on 2024-04-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_rename_seattype_airplane_seats_remove_flight_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
    ]
