# Generated by Django 5.0.3 on 2024-04-11 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_remove_flight_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='Airplane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.airplane'),
        ),
    ]
