# Generated by Django 5.0.3 on 2024-04-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0018_flight_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='price',
            new_name='price_flight',
        ),
    ]
