# Generated by Django 5.0.4 on 2024-04-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0019_rename_price_flight_price_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
