# Generated by Django 5.0.3 on 2024-04-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0020_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='comment',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
