# Generated by Django 5.0.3 on 2024-05-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0024_alter_flight_destination_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_schedule',
            field=models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Transit', 'Transit')], max_length=100, null=True),
        ),
    ]
