# Generated by Django 5.0.3 on 2024-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
